// Montaje del videocurso. Tiempos en segundos del bruto (= segundos del mezzanine).
// Los segmentos salen de scripts/cortes.mjs (tomas elegidas a mano + VAD) → cortes.json.
// Los gráficos explican lo que dice la ponente en ese momento; sus marcas (`en`) son el instante
// en que se nombra cada elemento. Sin nombres propios ni datos personales.
import cortes from "./cortes.json";
import type { Capitulo, Enfasis, Grafico } from "./tipos";

export const CURSO = {
  kicker: "RESILIENCIA OPERATIVA DIGITAL",
  titulo1: "DORA en",
  titulo2: "la práctica",
  subtitulo: "Tres casos reales para decidir como exige el reglamento",
  fantasma: "RESILIENCIA",
  rotuloDocente: "Docente del curso",
  rotuloTema: "DORA · Casos prácticos",
  ideas: [
    "La due diligence va antes de firmar, nunca después",
    "Ante una señal crítica, activar pronto cuesta menos que llegar tarde",
    "Resiliencia es ejecutar lo que ya tenías preparado",
  ],
  lema: "Academia de vídeo programático",
  pie: "FIN DEL MÓDULO · DORA EN LA PRÁCTICA",
};

const cap = (id: string) => cortes.capitulos.find((c) => c.id === id)!;

export const CAPITULOS: Capitulo[] = [
  {
    id: "caso1",
    numero: 1,
    titulo: "El proveedor que ya conocemos",
    subtitulo: "Contratar un SaaS con un proveedor certificado",
    secciones: cap("caso1").secciones,
    segmentos: cap("caso1").segmentos,
  },
  {
    id: "caso2",
    numero: 2,
    titulo: "La señal débil de las 9:15",
    subtitulo: "Una alerta sin confirmar que toca funciones críticas",
    secciones: cap("caso2").secciones,
    segmentos: cap("caso2").segmentos,
  },
  {
    id: "caso3",
    numero: 3,
    titulo: "Viernes por la tarde",
    subtitulo: "Portátil bloqueado y un plazo regulatorio a las 18:00",
    secciones: cap("caso3").secciones,
    segmentos: cap("caso3").segmentos,
  },
];

const OPC1 = [
  { letra: "A", texto: "Pack acelerado" },
  { letra: "B", texto: "Reutilización interna" },
  { letra: "C", texto: "Marco completo" },
  { letra: "D", texto: "Estrategia conservadora" },
];
const OPC2 = [
  { letra: "A", texto: "Confirmación primero" },
  { letra: "B", texto: "Activación preliminar del protocolo" },
  { letra: "C", texto: "Aislar y comunicar después" },
  { letra: "D", texto: "Decisión de las áreas afectadas" },
];
const OPC3 = [
  { letra: "A", texto: "Equipo del compañero" },
  { letra: "B", texto: "VDI desde dispositivo personal" },
  { letra: "C", texto: "Activación del protocolo" },
  { letra: "D", texto: "Decisión del responsable" },
];

export const GRAFICOS: Grafico[] = [
  // ═════════ CASO 1 · El proveedor que ya conocemos ═════════
  {
    tipo: "lista",
    t: 41.2,
    hasta: 68.9,
    disp: "esquina",
    kicker: "Caso 1 · Enunciado",
    titulo: "Un SaaS de analítica para el banco",
    items: [
      { en: 42.5, texto: "Herramienta SaaS de analítica avanzada", icono: "nube" },
      { en: 49.1, texto: "Fintech europea bien posicionada", icono: "red" },
      { en: 53.7, texto: "ISO 27001 · SOC 2 tipo 2 · referencias en bancos", icono: "escudo" },
      { en: 61.2, texto: "Tratará datos operativos y de funciones de cliente", icono: "datos" },
    ],
  },
  { tipo: "clave", t: 104.4, hasta: 111.6, texto: "Negocio quiere cerrarlo este trimestre", sub: "¿Cómo lo abordas?" },
  {
    tipo: "opciones",
    t: 138.9,
    hasta: 147.9,
    disp: "dividida",
    kicker: "Caso 1 · Opciones",
    titulo: "¿Cómo lo abordas?",
    opciones: OPC1,
    foco: { letra: "A", en: 146.7, veredicto: "trampa" },
  },
  {
    tipo: "comparativa",
    t: 148.0,
    hasta: 156.3,
    disp: "dividida",
    kicker: "Certificación ≠ contrato",
    izq: { titulo: "Certificaciones", items: ["ISO 27001", "SOC 2", "Útiles, pero no bastan"], tono: "neutro", en: 148.2 },
    der: { titulo: "Cláusulas DORA", items: ["Específicas", "Obligatorias en el contrato"], tono: "ok", en: 152.5 },
  },
  {
    tipo: "escena3d",
    t: 166.1,
    hasta: 187.3,
    disp: "esquina",
    kicker: "Artículo 30 del reglamento",
    titulo: "Lo que el contrato tiene que incluir",
    escena: "contrato",
    etiquetas: [
      { en: 170.0, texto: "Derechos de auditoría" },
      { en: 172.1, texto: "Gestión de subcontratistas" },
      { en: 173.8, texto: "Asistencia y portabilidad en la salida" },
      { en: 176.6, texto: "Cooperación con autoridades" },
      { en: 184.2, texto: "Casi ningún contrato estándar lo cubre" },
    ],
  },
  {
    tipo: "comparativa",
    t: 198.4,
    hasta: 229.3,
    disp: "dividida",
    kicker: "El orden importa",
    izq: {
      titulo: "Después de firmar",
      items: ["Poder de negociación cero", "Si hay riesgo, sin palanca"],
      tono: "bad",
      en: 202.4,
    },
    der: {
      titulo: "Antes de firmar",
      items: ["Negocias las cláusulas", "Decides con información"],
      tono: "ok",
      en: 220.0,
    },
  },
  {
    tipo: "cita",
    t: 229.35,
    hasta: 233.3,
    disp: "dividida",
    kicker: "Idea clave",
    texto: "La due diligence es prerrequisito de la firma, no una tarea de onboarding.",
    resalta: ["prerrequisito", "firma,"],
  },
  {
    tipo: "opciones",
    t: 235.8,
    hasta: 246.3,
    disp: "dividida",
    kicker: "Caso 1 · Opciones",
    titulo: "¿Cómo lo abordas?",
    opciones: OPC1,
    foco: { letra: "B", en: 239.1, veredicto: "riesgo" },
  },
  {
    tipo: "mapa",
    t: 246.5,
    hasta: 272.9,
    disp: "esquina",
    kicker: "Cada relación se evalúa según su uso",
    centro: "Relación con el proveedor",
    ramas: [
      { en: 257.4, texto: "Riesgos concretos" },
      { en: 258.9, texto: "Datos concretos" },
      { en: 260.3, texto: "Caso de uso concreto" },
      { en: 265.9, texto: "Criticidad de la función" },
      { en: 269.5, texto: "Nivel de impacto si falla" },
    ],
  },
  {
    tipo: "clave",
    t: 273.5,
    hasta: 282.5,
    texto: "Reaprovechar un contrato",
    sub: "es aceptar cláusulas pensadas para otro caso",
  },
  {
    tipo: "comparativa",
    t: 282.8,
    hasta: 290.4,
    disp: "esquina",
    kicker: "Otro uso, otro riesgo",
    izq: { titulo: "Allí", items: ["Dato no crítico", "Subcontratación que servía"], tono: "neutro", en: 282.9 },
    der: { titulo: "Aquí", items: ["Dato sensible", "Puede no servirte"], tono: "bad", en: 285.3 },
  },
  {
    tipo: "escena3d",
    t: 290.5,
    hasta: 299.8,
    disp: "esquina",
    kicker: "Registro de información",
    titulo: "Cada relación se inscribe por separado",
    escena: "registro",
    etiquetas: [
      { en: 292.1, texto: "Relación de servicio 1" },
      { en: 294.1, texto: "Relación de servicio 2" },
      { en: 298.1, texto: "«Ya estaba el otro proveedor» no vale" },
    ],
  },
  {
    tipo: "opciones",
    t: 435.15,
    hasta: 459.4,
    disp: "dividida",
    kicker: "Caso 1 · Opciones",
    titulo: "¿Cómo lo abordas?",
    opciones: OPC1,
    foco: { letra: "C", en: 455.7, veredicto: "correcta" },
  },
  {
    tipo: "pasos",
    t: 459.5,
    hasta: 482.5,
    disp: "dividida",
    kicker: "Lo que pide el capítulo V de DORA",
    titulo: "El marco completo",
    pasos: [
      { en: 460.7, texto: "Clasificación previa por criticidad", icono: "lupa" },
      { en: 462.7, texto: "Due diligence específica para tu caso", icono: "auditoria" },
      { en: 465.7, texto: "Contrato con cláusulas mínimas", icono: "contrato" },
      { en: 477.5, texto: "Inscripción en el registro", icono: "registro" },
      { en: 479.4, texto: "Escalado a dirección si es crítica", icono: "banco" },
    ],
  },
  {
    tipo: "lista",
    t: 483.9,
    hasta: 494.3,
    disp: "esquina",
    kicker: "Lo que parece burocracia…",
    titulo: "…es lo que te preguntará el supervisor",
    items: [
      { en: 491.8, texto: "¿Con quién?", icono: "personas" },
      { en: 492.3, texto: "¿Para qué?", icono: "lupa" },
      { en: 493.2, texto: "¿Bajo qué condiciones?", icono: "contrato" },
    ],
  },
  {
    tipo: "escena3d",
    t: 494.35,
    hasta: 505.6,
    disp: "esquina",
    kicker: "Estrategia de salida",
    titulo: "¿Cómo saldrías si el proveedor desaparece?",
    escena: "salida",
    etiquetas: [{ en: 495.0, texto: "Salida ordenada del contrato" }],
  },
  {
    tipo: "opciones",
    t: 592.0,
    hasta: 640.0,
    disp: "dividida",
    kicker: "Caso 1 · Opciones",
    titulo: "¿Cómo lo abordas?",
    opciones: OPC1,
    foco: { letra: "D", en: 594.7, veredicto: "riesgo" },
  },
  {
    tipo: "comparativa",
    t: 640.0,
    hasta: 657.9,
    disp: "dividida",
    kicker: "Riesgo de concentración · art. 29",
    izq: {
      titulo: "Lo que pide DORA",
      items: ["Gestionar el riesgo de cada proveedor", "Vigilar la concentración"],
      tono: "ok",
      en: 640.0,
    },
    der: { titulo: "Conclusión equivocada", items: ["Reducir el número de proveedores"], tono: "bad", en: 649.9 },
  },
  {
    tipo: "escena3d",
    t: 658.2,
    hasta: 675.9,
    disp: "esquina",
    kicker: "Concentrarse en un solo proveedor",
    titulo: "Si se cae, se cae todo lo que depende de él",
    escena: "cadena",
    etiquetas: [
      { en: 658.4, texto: "Banco" },
      { en: 659.3, texto: "Proveedor único" },
      { en: 665.5, texto: "Servicios dependientes" },
      { en: 674.5, texto: "Nuevas dependencias" },
    ],
  },
  {
    tipo: "lista",
    t: 682.3,
    hasta: 690.2,
    disp: "dividida",
    kicker: "La pregunta correcta",
    titulo: "¿Cada relación está bien…?",
    items: [
      { en: 687.5, texto: "Evaluada", icono: "lupa" },
      { en: 688.1, texto: "Contratada", icono: "contrato" },
      { en: 688.8, texto: "Inscrita", icono: "registro" },
      { en: 689.4, texto: "Monitorizada", icono: "reloj" },
    ],
  },

  // ═════════ CASO 2 · La señal débil de las 9:15 ═════════
  {
    tipo: "lista",
    t: 743.0,
    hasta: 754.3,
    disp: "esquina",
    kicker: "Caso 2 · Lunes, 9:15",
    titulo: "Salta una alerta",
    items: [
      { en: 746.7, texto: "Comportamiento anómalo detectado", icono: "alerta" },
      { en: 749.2, texto: "App interna usada por varios equipos", icono: "personas" },
      { en: 752.9, texto: "Incluye áreas operativas críticas", icono: "banco" },
    ],
  },
  {
    tipo: "contador",
    t: 766.2,
    hasta: 782.6,
    disp: "esquina",
    kicker: "Contexto",
    cifras: [
      { en: 772.3, valor: 6, sufijo: " meses", etiqueta: "de historial reciente" },
      { en: 773.9, valor: 3, etiqueta: "alertas similares, todas falsas" },
      { en: 777.9, valor: 0, etiqueta: "quejas de usuarios por ahora" },
    ],
  },
  { tipo: "clave", t: 782.8, hasta: 787.7, texto: "Eres el analista de turno", sub: "Decides en los próximos minutos" },
  {
    tipo: "opciones",
    t: 802.3,
    hasta: 820.9,
    disp: "dividida",
    kicker: "Caso 2 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC2,
    foco: { letra: "A", en: 818.2, veredicto: "trampa" },
  },
  { tipo: "clave", t: 821.1, hasta: 826.0, texto: "Artículo 17", sub: "Detección, gestión y notificación rápidas" },
  {
    tipo: "linea",
    t: 861.8,
    hasta: 879.8,
    disp: "esquina",
    kicker: "El reloj regulatorio",
    titulo: "Esperar también cuenta",
    hitos: [
      { en: 862.8, texto: "Alerta detectada" },
      { en: 868.7, texto: "Se clasifica como grave: arranca el reloj", marca: "warn" },
      { en: 873.3, texto: "Dos horas «confirmando»", marca: "warn" },
      { en: 877.9, texto: "Dos horas regaladas", marca: "bad" },
    ],
  },
  {
    tipo: "lista",
    t: 880.0,
    hasta: 894.05,
    disp: "esquina",
    kicker: "En esas dos horas",
    titulo: "Un atacante puede…",
    items: [
      { en: 882.1, texto: "Moverse lateralmente", icono: "red" },
      { en: 883.4, texto: "Escalar privilegios", icono: "candado" },
      { en: 884.8, texto: "Exfiltrar datos", icono: "datos" },
    ],
  },
  {
    tipo: "cita",
    t: 900.6,
    hasta: 905.1,
    disp: "dividida",
    kicker: "Ante el supervisor",
    texto: "Tu primera línea defensiva habrá sido esperar. Muy difícil de defender.",
    resalta: ["esperar."],
  },
  {
    tipo: "opciones",
    t: 907.4,
    hasta: 915.7,
    disp: "dividida",
    kicker: "Caso 2 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC2,
    foco: { letra: "B", en: 911.8, veredicto: "correcta" },
  },
  {
    tipo: "comparativa",
    t: 926.7,
    hasta: 938.4,
    disp: "dividida",
    kicker: "La clave: «preliminar»",
    izq: { titulo: "No estás…", items: ["Declarando un incidente grave"], tono: "bad", en: 926.9 },
    der: {
      titulo: "Sí estás…",
      items: ["Activando el protocolo en su grado más bajo", "Cubriendo una alerta no confirmada"],
      tono: "ok",
      en: 928.8,
    },
  },
  {
    tipo: "pasos",
    t: 1073.3,
    hasta: 1089.7,
    disp: "dividida",
    kicker: "Dos cosas a la vez",
    titulo: "Activar en grado preliminar te permite",
    pasos: [
      { en: 1082.1, texto: "Actuar técnicamente: contención, evidencias, impacto", icono: "escudo" },
      { en: 1086.5, texto: "Tener el reloj regulatorio bajo control", icono: "reloj" },
    ],
  },
  {
    tipo: "comparativa",
    t: 1091.4,
    hasta: 1101.3,
    disp: "dividida",
    kicker: "Pase lo que pase",
    izq: { titulo: "Falso positivo", items: ["Cierras, registras y aprendes"], tono: "ok", en: 1091.6 },
    der: { titulo: "Incidente real", items: ["Todo en marcha desde el minuto cero"], tono: "ok", en: 1098.7 },
  },
  {
    tipo: "escena3d",
    t: 1103.2,
    hasta: 1113.2,
    disp: "esquina",
    kicker: "La filosofía de DORA",
    titulo: "Activar pronto siempre sale más barato",
    escena: "balanza",
    etiquetas: [
      { en: 1109.0, texto: "Coste de activar y desactivar" },
      { en: 1112.1, texto: "Coste de no activar a tiempo" },
      { en: 1112.5, texto: "(pesa mucho más)" },
    ],
  },
  {
    tipo: "opciones",
    t: 1115.1,
    hasta: 1128.7,
    disp: "dividida",
    kicker: "Caso 2 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC2,
    foco: { letra: "C", en: 1119.3, veredicto: "riesgo" },
  },
  {
    tipo: "lista",
    t: 1131.7,
    hasta: 1167.2,
    disp: "esquina",
    kicker: "Aislar sin protocolo deja cabos sueltos",
    titulo: "Preguntas sin dueño",
    items: [
      { en: 1143.7, texto: "¿Quién clasifica el incidente y con qué criterio?", icono: "lupa" },
      { en: 1146.6, texto: "¿Quién preserva las evidencias forenses?", icono: "auditoria" },
      { en: 1150.1, texto: "¿Se ha evaluado el impacto en funciones críticas?", icono: "banco" },
      { en: 1154.5, texto: "¿Está activado el reloj regulatorio?", icono: "reloj" },
      { en: 1160.6, texto: "¿Quién gestiona la indisponibilidad para clientes?", icono: "personas" },
    ],
  },
  {
    tipo: "mapa",
    t: 1169.6,
    hasta: 1181.8,
    disp: "esquina",
    kicker: "Contención dentro de un protocolo",
    centro: "Protocolo de incidentes",
    ramas: [
      { en: 1178.2, texto: "Registro" },
      { en: 1179.5, texto: "Evaluación de impacto" },
      { en: 1180.4, texto: "Escalado" },
      { en: 1181.0, texto: "Comunicación" },
    ],
  },
  {
    tipo: "clave",
    t: 1309.3,
    hasta: 1316.6,
    texto: "«Aislar y comunicar después»",
    sub: "Técnicamente maduro, pero sin disciplina regulatoria",
  },
  {
    tipo: "opciones",
    t: 1319.1,
    hasta: 1340.4,
    disp: "dividida",
    kicker: "Caso 2 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC2,
    foco: { letra: "D", en: 1333.4, veredicto: "trampa" },
  },
  {
    tipo: "comparativa",
    t: 1342.1,
    hasta: 1382.0,
    disp: "dividida",
    kicker: "¿Quién decide qué?",
    izq: {
      titulo: "Seguridad TIC",
      items: ["Activa el protocolo", "Sin esperar aprobación previa"],
      tono: "ok",
      en: 1355.5,
    },
    der: {
      titulo: "Negocio",
      items: ["Prioridades de servicio", "Comunicación a clientes", "Aceptación del impacto"],
      tono: "neutro",
      en: 1371.7,
    },
  },
  {
    tipo: "linea",
    t: 1384.1,
    hasta: 1403.0,
    disp: "esquina",
    kicker: "Esperar permiso mete latencia humana",
    titulo: "Un proceso que DORA quiere automático",
    hitos: [
      { en: 1389.3, texto: "15 minutos", marca: "warn" },
      { en: 1390.2, texto: "Una hora", marca: "warn" },
      { en: 1390.8, texto: "Una mañana entera", marca: "bad" },
      { en: 1397.9, texto: "Defensa que no se sostiene", marca: "bad" },
    ],
  },

  // ═════════ CASO 3 · Viernes por la tarde ═════════
  {
    tipo: "lista",
    t: 1444.2,
    hasta: 1470.3,
    disp: "esquina",
    kicker: "Caso 3 · Viernes por la tarde",
    titulo: "Todo falla a la peor hora",
    items: [
      { en: 1444.4, texto: "Entrega crítica con plazo a las 18:00", icono: "reloj" },
      { en: 1447.5, texto: "Reporte regulatorio, cierre operativo, nómina…", icono: "registro" },
      { en: 1457.0, texto: "El portátil corporativo se bloquea", icono: "alerta" },
      { en: 1466.7, texto: "El trabajo está en red, pero sin equipo no accedes", icono: "datos" },
    ],
  },
  {
    tipo: "contador",
    t: 1479.3,
    hasta: 1482.7,
    disp: "esquina",
    kicker: "Tiempo disponible",
    cifras: [{ en: 1479.8, valor: 90, sufijo: " min", etiqueta: "para decidir y entregar" }],
  },
  {
    tipo: "opciones",
    t: 1502.1,
    hasta: 1517.8,
    disp: "dividida",
    kicker: "Caso 3 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC3,
    foco: { letra: "A", en: 1504.9, veredicto: "trampa" },
  },
  {
    tipo: "pasos",
    t: 1517.9,
    hasta: 1548.1,
    disp: "dividida",
    kicker: "Rompe varios principios a la vez",
    titulo: "1 · Trazabilidad del dispositivo",
    pasos: [
      { en: 1521.4, texto: "Tu sesión, en un equipo asignado a otra persona", icono: "personas" },
      { en: 1535.6, texto: "Los logs del SIEM lo registran así", icono: "registro" },
      { en: 1546.5, texto: "La investigación forense se complica", icono: "auditoria" },
    ],
  },
  {
    tipo: "lista",
    t: 1549.95,
    hasta: 1582.5,
    disp: "esquina",
    kicker: "2 · Segregación y configuración",
    titulo: "Heredas lo que no es tuyo",
    items: [
      { en: 1562.2, texto: "Perfiles, herramientas y permisos de otro rol", icono: "personas" },
      { en: 1572.2, texto: "Certificados y accesos guardados", icono: "candado" },
      { en: 1574.4, texto: "Software específico", icono: "datos" },
      { en: 1579.4, texto: "Un entorno distinto al que exige tu rol", icono: "alerta" },
    ],
  },
  {
    tipo: "clave",
    t: 1584.4,
    hasta: 1597.5,
    texto: "3 · Política de uso de equipos",
    sub: "Prestar el equipo asignado es una infracción explícita",
  },
  {
    tipo: "cita",
    t: 1599.45,
    hasta: 1603.7,
    disp: "dividida",
    kicker: "Idea clave",
    texto: "Si lo que rompe la regla es una excepción puntual, la regla se erosiona.",
    resalta: ["erosiona."],
  },
  {
    tipo: "opciones",
    t: 1606.3,
    hasta: 1616.3,
    disp: "dividida",
    kicker: "Caso 3 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC3,
    foco: { letra: "B", en: 1611.5, veredicto: "riesgo" },
  },
  {
    tipo: "comparativa",
    t: 1616.4,
    hasta: 1651.5,
    disp: "dividida",
    kicker: "El VDI no lo arregla todo",
    izq: {
      titulo: "Lo que sí protege",
      items: ["Encapsula la sesión", "Restringe la salida de datos"],
      tono: "ok",
      en: 1622.4,
    },
    der: { titulo: "Lo que no", items: ["El dispositivo desde el que te conectas"], tono: "bad", en: 1651.55 },
  },
  {
    tipo: "lista",
    t: 1651.6,
    hasta: 1663.7,
    disp: "esquina",
    kicker: "Tu tablet personal",
    titulo: "Un dispositivo no gestionado",
    items: [
      { en: 1657.2, texto: "Sin EDR corporativo", icono: "cruz" },
      { en: 1658.5, texto: "Sin inventario", icono: "cruz" },
      { en: 1659.5, texto: "Sin garantías de parche", icono: "cruz" },
      { en: 1661.0, texto: "Sin cifrado controlado", icono: "cruz" },
      { en: 1662.5, texto: "Sin política de actualizaciones", icono: "cruz" },
    ],
  },
  {
    tipo: "lista",
    t: 1665.8,
    hasta: 1685.1,
    disp: "esquina",
    kicker: "Si la tablet está comprometida…",
    titulo: "…todo lo que ves en el VDI se filtra",
    items: [
      { en: 1672.1, texto: "Keylogger", icono: "alerta" },
      { en: 1673.0, texto: "Screen scraper", icono: "alerta" },
      { en: 1674.3, texto: "Malware de captura de portapapeles", icono: "alerta" },
      { en: 1680.9, texto: "La virtualización no protege la captura", icono: "escudo" },
    ],
  },
  {
    tipo: "clave",
    t: 1687.4,
    hasta: 1695.6,
    texto: "Solo dispositivos gestionados",
    sub: "para acceder a sistemas críticos",
  },
  {
    tipo: "cita",
    t: 1719.75,
    hasta: 1727.7,
    disp: "dividida",
    kicker: "Idea clave",
    texto: "Saltárselo porque todo va por VDI es shadow IT vestido de buena ingeniería.",
    resalta: ["shadow", "IT", "ingeniería."],
  },
  {
    tipo: "opciones",
    t: 1758.4,
    hasta: 1766.8,
    disp: "dividida",
    kicker: "Caso 3 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC3,
    foco: { letra: "C", en: 1761.1, veredicto: "correcta" },
  },
  {
    tipo: "comparativa",
    t: 1780.65,
    hasta: 1788.6,
    disp: "dividida",
    kicker: "Clasifica bien el incidente",
    izq: { titulo: "No es…", items: ["«Se me ha roto el portátil»"], tono: "bad", en: 1781.0 },
    der: { titulo: "Es…", items: ["Riesgo de incumplir un plazo por un fallo TIC"], tono: "ok", en: 1783.0 },
  },
  {
    tipo: "pasos",
    t: 1789.5,
    hasta: 1803.6,
    disp: "dividida",
    kicker: "Lo que espera un banco maduro",
    titulo: "Actúas en paralelo",
    pasos: [
      { en: 1789.7, texto: "Comunicas a soporte TIC, responsable y área", icono: "personas" },
      { en: 1797.4, texto: "Activas el plan de continuidad", icono: "escudo" },
      { en: 1802.0, texto: "Documentas desde el minuto 1", icono: "registro" },
    ],
  },
  {
    tipo: "linea",
    t: 1864.05,
    hasta: 1873.6,
    disp: "esquina",
    kicker: "Deja preparado el siguiente escalón",
    titulo: "Por si el plazo se incumple",
    hitos: [
      { en: 1864.2, texto: "Plan de continuidad activo", marca: "ok" },
      { en: 1868.4, texto: "Procedimiento de incidente operativo", marca: "warn" },
      { en: 1870.6, texto: "Notificaciones internas", marca: "warn" },
      { en: 1872.5, texto: "Y, si aplica, regulatorias", marca: "warn" },
    ],
  },
  {
    tipo: "escena3d",
    t: 1876.55,
    hasta: 1883.55,
    disp: "esquina",
    kicker: "Idea clave",
    titulo: "Eso es resiliencia operativa",
    escena: "escudo",
    etiquetas: [
      { en: 1876.8, texto: "Ser ágil no es improvisar" },
      { en: 1879.9, texto: "Es ejecutar lo que ya tenías preparado" },
    ],
  },
  {
    tipo: "opciones",
    t: 1886.3,
    hasta: 1901.3,
    disp: "dividida",
    kicker: "Caso 3 · Opciones",
    titulo: "¿Qué decisión tomas?",
    opciones: OPC3,
    foco: { letra: "D", en: 1893.9, veredicto: "riesgo" },
  },
  {
    tipo: "pasos",
    t: 1902.4,
    hasta: 1916.75,
    disp: "dividida",
    kicker: "En paralelo, no esperando un correo",
    titulo: "Lo que tienes que activar tú",
    pasos: [
      { en: 1902.8, texto: "Ticket en soporte TIC", icono: "contrato" },
      { en: 1905.2, texto: "Plan de continuidad", icono: "escudo" },
      { en: 1907.0, texto: "Aviso al área funcional", icono: "personas" },
    ],
  },
  {
    tipo: "comparativa",
    t: 1927.45,
    hasta: 1943.2,
    disp: "dividida",
    kicker: "El papel de tu responsable",
    izq: { titulo: "No decide…", items: ["Si llamas a IT"], tono: "bad", en: 1930.2 },
    der: { titulo: "Sí decide…", items: ["¿Pedimos prórroga?", "¿Quién avisa a cumplimiento?"], tono: "ok", en: 1934.2 },
  },
  {
    tipo: "contador",
    t: 2000.0,
    hasta: 2013.9,
    disp: "esquina",
    kicker: "Reiniciar otra vez por tu cuenta",
    cifras: [{ en: 2006.7, valor: 30, sufijo: " min", etiqueta: "la primera media hora: el tiempo más valioso" }],
  },
  {
    tipo: "clave",
    t: 2014.0,
    hasta: 2022.7,
    texto: "Los reinicios forzados",
    sub: "pueden complicar la recuperación de datos por parte de IT",
  },
];

// Zooms de énfasis (punch-in suave anclado en la cara) en las frases clave.
export const ENFASIS: Enfasis[] = [
  { t: 146.6, dur: 1.6 }, // "Pero aquí está la trampa"
  { t: 239.0, dur: 2.2 }, // "la más peligrosa de las cuatro"
  { t: 280.5, dur: 1.4 }, // "normalmente eso no es verdad"
  { t: 648.0, dur: 3.0 }, // "Hasta aquí, bien. Pero la conclusión es la equivocada"
  { t: 665.4, dur: 2.6 }, // "Si se cae, se cae todo"
  { t: 818.1, dur: 1.8 }, // "El problema es que DORA no te deja esperar"
  { t: 913.9, dur: 1.8 }, // "La clave está en la palabra preliminar"
  { t: 1119.2, dur: 3.0 }, // "cerca de la respuesta correcta… la más fácil de elegir mal"
  { t: 1167.6, dur: 1.8 }, // "La contención sin protocolo es un acto técnico aislado"
  { t: 1394.8, dur: 2.5 }, // "tu defensa ante el supervisor… no se sostiene"
  { t: 1508.9, dur: 1.6 }, // "hay que desmontarla con cuidado"
  { t: 1633.3, dur: 2.2 }, // "Pero el dispositivo desde el que te conectas…"
  { t: 1882.4, dur: 1.2, zoom: 1.2 }, // "Eso es resiliencia operativa"
  { t: 2003.5, dur: 2.5 }, // "Estás perdiendo el tiempo más valioso"
];
